function bat_path = create_batfile(options, output_dir)
%CREATE_BATFILE 実行用バッチファイルを作成する
%
%   bat_path = create_batfile(options, output_dir)
%
%   Input:
%       options - CommonOption オブジェクト
%       output_dir - バッチファイルの保存先ディレクトリ (省略時はpwd)
%
%   Output:
%       bat_path - 作成されたバッチファイルのフルパス

% 実行中EXEパスが未確定（MATLAB実行時）ではbatを生成できない
if isempty(options.exepath)
  error('CreateBatfile:NoExepath', ...
    'EXEの場所が確定しないため、batファイルを生成できません');
end

if nargin < 2
  output_dir = pwd;
end

% バッチファイル名の決定（入力ファイル名ベース）
[~, name, ~] = fileparts(options.inputfile);
if isempty(name)
  name = 'ylab_run';
end
bat_name = ['run_' name '.bat'];
bat_path = fullfile(output_dir, bat_name);

fid = fopen(bat_path, 'w');
if fid == -1
  error('Failed to create batch file: %s', bat_path);
end
cleanupObj = onCleanup(@() fclose(fid));

fprintf(fid, '@echo off\r\n');
fprintf(fid, 'setlocal\r\n');
fprintf(fid, 'rem Generated by YLAB Settings Dialog\r\n');
fprintf(fid, 'rem Date: %s\r\n', char(datetime('now')));
fprintf(fid, '\r\n');

fprintf(fid, 'set EXE_PATH="%s"\r\n', options.exepath);
fprintf(fid, '\r\n');

fprintf(fid, 'echo Running YLAB...\r\n');
fprintf(fid, '%%EXE_PATH%% ^\r\n');
fprintf(fid, '  uimode CUI ^\r\n');
fprintf(fid, '  exemode %s ^\r\n', options.exemode);
fprintf(fid, '  inputfile "%s" ^\r\n', options.inputfile);
fprintf(fid, '  outputfile "%s"', options.outputfile);

% PDFオプション
if ~options.do_writeout_pdf
  fprintf(fid, ' ^\r\n  -nopdf');
end

% 断面リスト事前処理オプション
if ~options.do_preprocess_section_list
  fprintf(fid, ' ^\r\n  -nopreprocess');
end

fprintf(fid, '\r\n');
fprintf(fid, '\r\n');

% エラーハンドリング
fprintf(fid, 'if errorlevel 1 (\r\n');
fprintf(fid, ...
  '    echo Execution failed with error level %%errorlevel%%\r\n');
fprintf(fid, '    pause\r\n');
fprintf(fid, ')\r\n');

fprintf(fid, 'endlocal\r\n');
end
