function script_path = create_mscript(options, approot, output_dir, original_output_file, do_copy)
% CREATE_MSCRIPT 実行用MATLABスクリプトを作成する

[~, n, ~] = fileparts(options.inputfile);
if isempty(n), n = 'ylab_run'; end

    script_name = ['run_' n '.m'];script_path = fullfile(output_dir, script_name);

fid = fopen(script_path, 'w');
if fid == -1
  error('Failed to create file: %s', script_path);
end
cleanupObj = onCleanup(@() fclose(fid));

% Header
fprintf(fid, '%% Generated by YLAB Settings Dialog\n');
fprintf(fid, '%% Date: %s\n\n', datestr(now));

% Path setting
approot = strrep(approot, '\', '/');
fprintf(fid, 'approot = ''%s'';\n', approot);
fprintf(fid, 'addpath(approot);\n');
fprintf(fid, 'install;\n\n');

% File settings
inputfile_ = strrep(options.inputfile, '\', '/');
outputfile_ = strrep(options.outputfile, '\', '/');

fprintf(fid, 'inputfile = ''%s'';\n', inputfile_);
fprintf(fid, 'outputfile = ''%s'';\n\n', outputfile_);

% Main execution block
fprintf(fid, 'try\n');
fprintf(fid, '    YLAB( ...\n');
fprintf(fid, '        ''uimode'', ''CUI'', ...\n');
fprintf(fid, '        ''exemode'', ''%s'', ...\n', options.exemode);
fprintf(fid, '        ''inputfile'', inputfile, ...\n');

% Optional parameters
if ~isempty(options.matfile)
  fprintf(fid, '        ''matfile'', ''%s'', ...\n', strrep(options.matfile, '\', '/'));
end
if options.idtrial_resume > 1
  fprintf(fid, '        ''idtrial_resume'', %d, ...\n', options.idtrial_resume);
end
if options.idphase_resume > 1
  fprintf(fid, '        ''idphase_resume'', %d, ...\n', options.idphase_resume);
end
if options.iter_resume > 0
  fprintf(fid, '        ''iter_resume'', %d, ...\n', options.iter_resume);
end
if isfinite(options.maxphase)
  fprintf(fid, '        ''maxphase'', %d, ...\n', options.maxphase);
end
if isfinite(options.maxiter_in_LS)
  fprintf(fid, '        ''maxiter'', %d, ...\n', options.maxiter_in_LS);
end
if options.idtrial > 0
  fprintf(fid, '        ''trial'', %d, ...\n', options.idtrial);
end
if options.do_writeout_pdf
  fprintf(fid, '        ''-pdf'', ...\n');
else
  fprintf(fid, '        ''-nopdf'', ...\n');
end

% Close YLAB call
fprintf(fid, '        ''outputfile'', outputfile);\n');

% Catch block
fprintf(fid, 'catch ME\n');
fprintf(fid, '    disp(ME.message);\n');
fprintf(fid, 'end\n');

% Copy block
if do_copy && ~isempty(original_output_file)
  target_ = strrep(original_output_file, '\', '/');
  fprintf(fid, '\n%% Copy to target\n');
  fprintf(fid, 'if exist(outputfile, ''file'')\n');
  fprintf(fid, '    targetfile = ''%s'';\n', target_);
  fprintf(fid, '    dst_dir = fileparts(targetfile);\n');
  fprintf(fid, '    if ~exist(dst_dir, ''dir'') && ~isempty(dst_dir), mkdir(dst_dir); end\n');
  fprintf(fid, '    copyfile(outputfile, targetfile);\n');
  fprintf(fid, '    fprintf(''Copied result to target: %%s\n'', targetfile);\n');
  fprintf(fid, 'end\n');
end
end
