function buildYLAB
install
[~, res, ~] = YLAB('-version');
version = res.version;
devDate = res.devDate;
% tmpOut = "C:\temp\ylab_build";
% if exist(tmpOut,"dir"), rmdir(tmpOut,"s"); end
% mkdir(tmpOut);
results = compiler.build.standaloneApplication(...
  "YLAB.m", ...
  "OutputDir", "build", ...
  ..."OutputDir", tmpOut, ...
  ...'EmbedArchive','on',...
  "Verbose","on", ...
  "ExecutableVersion", version ...
  );

% インストーラー説明文の作成
description = sprintf([...
  'YLAB (Y-Lab Structural Optimization) is an advanced structural optimization program ' ...
  'for building frame design using local search algorithms.\n\n' ...
  'This application was developed on %s by Yamakawa Laboratory ' ...
  'at Tokyo University of Science (TUS).\n\n' ...
  'Features:\n' ...
  '• Comprehensive tools for optimizing steel frame structures\n' ...
  '• Support for H-beams, hollow sections, and buckling-restrained braces\n' ...
  '• Multiple execution modes: optimization analysis, result verification, and SS7 data conversion\n' ...
  '• Advanced local search algorithms for structural optimization\n\n' ...
  'Copyright (c) Yamakawa Laboratory, Tokyo University of Science'], devDate);

compiler.package.installer(results, ...
  "ApplicationName", "YLAB", ...
  "AuthorCompany", "TUS", ...
  "AuthorEmail", "myamakawa@rs.tus.ac.jp", ...
  "AuthorName", "Yamakawa Lab.", ...
  "InstallerName", "YLabInstaller", ...
  "Version", version, ...
  "DefaultInstallationDir","C:\\Program Files\TUS\YLAB", ...
  "OutputDir", "build", ...
  "Description", description, ...
  "Verbose","on")
end