% ---
% YLAB実行のひな形
% ---

% % --- T1モデルのデータ変換 ---
% YLAB uimode CUI ...
%   exemode CONVERT ...
%   inputfile data/SS7/T1_SS7_output.csv ...
%   outputfile data/T1_converted.csv

% % --- T1モデルの最適化計算 ---
% YLAB uimode CUI ...
%   inputfile data/T1_model.csv ...
%   outputfile out/T1_output.csv ...

% % --- T1モデルの最適化計算 ---
% YLAB uimode CUI -nopdf ...
%   exemode CHECK ...
%   -nopdf ...
%   inputfile data/T1R.csv ...
%   outputfile out/T1R_output.csv ...

% % --- T1モデルの結果確認 ---
% YLAB uimode CUI ...
%   exemode CHECK ...
%   -nopdf ...
%   inputfile data/T1_model.csv ...
%   outputfile out/T1_check.csv ...
%   solutionfile data/T1_solution.txt

% % --- S4モデルのデータ変換 ---
% YLAB uimode CUI ...
%   exemode CONVERT ...
%   inputfile data/SS7/S4_sekkeirei_SS7_output.csv ...
%   outputfile data/S4_sekkeirei_converted.csv

% % --- S4設計例の結果確認 ---
% YLAB uimode CUI ...
%   exemode CHECK ...
%   -nopdf ...
%   inputfile data/S4.csv ...
%   outputfile out/S4_sekkeirei_output.csv ...

% % --- S4モデルの最適化計算 ---
% YLAB uimode CUI ...
%   inputfile data/S4_model.csv ...
%   outputfile out/S4_output.csv ...

% % --- S4モデルの結果確認 ---
% YLAB uimode CUI ...
%   -nopdf ...
%   exemode CHECK ...
%   inputfile data/S4_model.csv ...
%   outputfile out/S4_check.csv ...
%   solutionfile data/S4_solution.txt
  
% % --- S4モデルの結果確認(PDFなし) ---
% YLAB uimode CUI ...
%   exemode CHECK ...
%   -nopdf  ...
%   inputfile data/S4_model.csv ...
%   outputfile out/S4_check.csv ...
%   optionfile data/options_yamakawa.csv ...
%   solutionfile data/S4_solution.txt

% % --- S4モデルの結果確認(PDFなし) ---
% YLAB uimode CUI ...
%   exemode CHECK ...
%   -nopdf  ...
%   inputfile data/S4_cost.csv ...
%   outputfile out/S4_cost_output.csv ...

% YLAB exemode CHECK -nopdf inputfile data/KG01.csv outputfile out/KG01_output.csv
YLAB exemode CHECK -nopdf inputfile data/UN02G.csv outputfile out/UN02G_output.csv